using '../main.bicep'

param environment = 'dev'
param location = 'centralus'
param baseName = 'helpdesk'
param dataverseUrl = 'https://org2d0673ab.crm.dynamics.com'
param dataverseClientId = '<DEV-DATAVERSE-CLIENT-ID>'
param graphClientId = '<DEV-GRAPH-CLIENT-ID>'
param sqlAdminGroupObjectId = 'ae56772c-f40e-45d4-90f6-d1b8c3934909'
param sqlAdminGroupName = 'HelpDesk-SQL-Admins-Dev'
